Fix Rails version to v6
In v7, the asset pipeline gem `sprockets` was removed, leading to
the following error when running the dummy application:
undefined method `assets' for an instance of
Rails::Application::Configuration (NoMethodError)